variable "environment" {}
variable "ecr_url" {}
variable "cluster_name" {}
variable "service_name" {}
variable "github_connection_arn" {}
variable "github_full_repo" {}
variable "github_branch" {}
variable "github_repo_url" {}
variable "s3_bucket" {}
